version: "3"

includes:
  testing: ./taskfiles/testing.yml
  build: ./taskfiles/build.yml
  linting: ./taskfiles/linting.yml
  setup: ./taskfiles/setup.yml

vars:
  RESULTS_DIR: "results"
  COVERAGE_DIR: "coverage"
  NODE_VERSION: "22.x"

tasks:
  default:
    desc: "Run everything"
    cmds:
      - task setup:project
      - task lint
      - task test

  show-tree:
    desc: "Show directory tree up to level 5"
    cmds:
      - tree -L 5
